import { ScaffoldConfig, ScanResult, GeneratedFile } from '../types';

export function generateReadme(
  config: ScaffoldConfig,
  scan: ScanResult,
  files: GeneratedFile[],
  smokeConfidence: number,
  workflowConfidences: number[]
): string {
  const date = new Date().toISOString().split('T')[0];
  const avgWorkflow =
    workflowConfidences.length > 0
      ? (workflowConfidences.reduce((a, b) => a + b, 0) / workflowConfidences.length).toFixed(2)
      : 'n/a';

  const fileTable = files
    .map((f) => {
      const conf = f.confidence != null ? f.confidence.toFixed(2) : '—';
      const desc = f.path.includes('smoke')
        ? `${scan.routes.length} smoke tests covering detected routes`
        : f.path.includes('workflows')
        ? 'Workflow test'
        : f.path.includes('playwright.config')
        ? 'Playwright configuration'
        : f.path.includes('run-tests')
        ? 'Local run script'
        : 'Generated file';
      return `| ${f.path} | ${desc} | ${conf} |`;
    })
    .join('\n');

  const startCommand = config.framework === 'angular' ? 'ng serve' : 'npm start';

  return `# Playwright Test Scaffold

Generated by CIB Scaffold Bootstrap Tool on ${date}.

## What was generated

| File | Description | Confidence |
|---|---|---|
${fileTable}

## How to run locally

### Prerequisites
- Node.js 18 or higher
- The app must be running locally on port ${scan.detectedPort}
- Start your app first: \`${startCommand}\`

### macOS / Linux
\`\`\`bash
bash e2e/run-tests.sh
\`\`\`

## Confidence summary

| Suite | Score |
|---|---|
| Smoke tests | ${smokeConfidence.toFixed(2)} |
| Workflow tests (avg) | ${avgWorkflow} |

## Review before trusting these tests

- Tests marked \`// FRAGILE\` use unstable selectors. Review these first.
- Tests with \`// TODO\` need manual verification against your actual UI.

## Next steps

1. Run the tests and check which pass on first run
2. Fix failures — update selectors and route paths to match your actual app
3. Add \`data-testid\` attributes where flagged as FRAGILE
4. Commit the \`e2e/\` directory and wire into your CI pipeline
`;
}
